version: '3.3'

services:
  web:
    image: klakegg/hugo:0.79.1-alpine
    container_name: hugo-container
    ports:
      - "1313:1313"
    volumes:
      - ./:/usr/local/iganari/iganari.github.io
    working_dir: /usr/local/iganari/iganari.github.io
    # command: /bin/sh  # for Debug
    # tty: true         # for Debug
    command: server --bind 0.0.0.0


