# refs: https://github.com/peaceiris/actions-hugo

name: github pages

on:
  push:
    branches:
    - master
    - feature/add-github-actions

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.61.0'
        # extended: true

    - name: Build
      run: |
        cd iganari-github-io
        git clone https://github.com/jpescador/hugo-future-imperfect.git themes/hugo-future-imperfect
        hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./iganari-github-io/public