# refs: https://github.com/peaceiris/actions-hugo

name: Publish_GitHub_Pages

on:
  push:
    branches:
    - release

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.79.1'
        # extended: true

    - name: Build
      run: |
        git clone https://github.com/matsuyoshi30/harbor.git themes/harbor
        hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public